name: CI-CD

on:
  push:
    # only trigger on branches, not on tags
    branches: '**'

jobs:
  job_id:
    permissions:
      contents: 'read'
      id-token: 'write'
#    env:
#       GIT_BRANCH : ${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
#       GIT_USER : ${{github.actor}}
    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        # Replace workload_identity_provider & service_account
        workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
        service_account: 'my-service-account@my-project.iam.gserviceaccount.com'

    - id: 'upload-pipelines-file (dev,acc,prd)'
      if:
        contains('
        refs/heads/develop
        refs/heads/release
        refs/heads/master
        ', github.ref)
      uses: 'google-github-actions/upload-cloud-storage@v0'
      with:
        path: '/path/to/file' # 'pipelines.yaml'
        destination: 'bucket-name/${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}_pipelines.yaml' # ex : develop_pipelines.yaml when commit to develop branch

    - id: 'upload-pipelines-file (sbx)'
      if:
        !contains('
        refs/heads/develop
        refs/heads/release
        refs/heads/master
        ', github.ref)
      uses: 'google-github-actions/upload-cloud-storage@v0'
      with:
        path: '/path/to/file' # 'pipelines.yaml'
        destination: 'bucket-name/${{github.actor}}_pipelines.yaml' # ex : yanargy_pipelines.yaml -> once uptaded, the cloud function is triggered